index.html
styles.css

This PR:
- Adds initial CSS styling for the single-page display
- Leaves borders on elements as final styles are TBD
- Adds global classes for re-use
- Creates a single-page, non overflow display
Needs:
- Mobile styling
- Font styling
- Color palette

Work through basic CSS display styling

---

index.html
styles.css

This PR:
- Makes the html page title all-caps
- Adds imported fonts to respective sections

Text styling

---

styles.css

Added:
- colors for buttons, cards, and header
Needs:
- better colors

Add placeholder colors

---

index.html
outfit.js
styles.css

Started working on the outfits.js class file
-wrote the first attempts at addGarment and removeGarment functions within the class

Outfit class

---

index.html
main.js

This PR:
- Replaces if statements in previous event listener functions which now allow items to be selected as well as deselected.
- Updated else statements in event listener functions to only allow a single item from each category added to the garments array at once.  
- Add values to HTML buttons to effectively track button clicks
Needs:
- Remove single nested if statement
- Reduce function length

Dressthebear

---

index.html
main.js
styles.css

This PR:
-Added function to display images in the DOM when corresponding button is clicked
Needs:
-Remove item when a new button is clicked

Add images

---

main.js

This PR:
- Adds functionality to hide the last selected item when a new one is clicked
Needs:
- Functionality to toggle the same item on and off

Add JS function to hide previous images

---

main.js

This PR:
- Fixes the bug wherein clicking on the active item doesn't visually deselect the choice

Fix image toggle bug

---

main.js

In this PR (group programmed):
- We added comments for each function in our main.js
- this allows us to quickly see exactly what each function is doing at a glance

:crystal_ball: Add comments for functions

---

index.html
main.js
styles.css

This PR (group programmed):
- we added an event listener to the save button below the name input field
- this fires a helper function called submitForm
- inside here a function called displayCard is fired which inserts a section of HTML which shows as a card on the right column of the page

Saved outfit card

---

main.js

This PR:
- we added a clearForm function that calls the reset() method on the input field DOM element
- clearForm is called inside the submitForm helper function

:crystal_ball: Add clearForm function

---

index.html
main.js
styles.css

In this PR (group programmed):
- we added form validation by using JS's built-in methods for inputs.
- if there is less than 3 characters in the input field, the button is disabled

Button disable

---

main.js

In this PR (group programmed):
- we added a clearBear function that loops through all items with the image-absolute class type and adds a 'hidden' class back to any active item
- the clearBear function is called on submit

:crystal_ball: Add clearBear function that is called on submit

---

main.js

This PR:
--Created function that disables save button once an outfit card has been created.

Disable Save button

---

main.js

This PR:
-Changed functionality in selectBackground() to populate button value into object class background array position.

:crystal_ball: Change selectBackground functionn

---

main.js

This PR:
**Group Coded**
--Added functionality to store array values in local storage.

:crystal_ball: Add functionality to store outfit array in local storage

---

main.js

This PR:
- Adds function to reset class instance on form submission

Add function to reset class instance on form submission

---

main.js

This PR:
- Adds function to load cards from local storage

Function to load cards from local storage

---

main.js

This PR:
- Added function to delete a selected card from local storage when the X is clicked.
-Proves that teamwork makes the dreamwork.
-Completes iteration 4

Added function to delete a card from local storage (Iteration 4 Complete)

---

main.js
outfit.js

This PR:
- Completes functionality for iteration 5

:crystal_ball: Add iteration 5 functionality

---

main.js
outfit.js

In this PR:
- We renamed a few functions to be more self explanatory

:crystal_ball: Added comments and renamed a few functions

---

index.html
styles.css

In this PR:
- We passed the chrome dev tools accessibility audit with 100% by following the feedback they provided.
- - This included adding alt tags, labeling the input form, and making foreground elements have more contrast.

:wheelchair: Added accessibility features

---

index.html
main.js
outfit.js
styles.css

In this PR:
- added an input field above the saved outfit cards
- added logic for filtering cards based on the characters in the search bar
-  added string method .startsWith so only beginning of title can meet search term

Outfit search

---

main.js
outfit.js
styles.css

In this PR:
- Added an animation class in CSS that affects the transform & opacity properties of the cards when they are populated.

:crystal_ball: Add animations for card population

---

index.html
main.js
styles.css

In this PR:
- We added in a card that prompts the use to add an outfit
- We added logic that hides the card if there are outfits saved and shows it if there aren't

:crystal_ball: Add banner functionality

---

index.html
styles.css

:ambulance: Fix placeholders not showing up

---

.vscode/settings.json
functions.js
index.html
main.js
outfit.js

This PR: 
- Adds a functions.js file to better organize code base

:crystal_ball: Organize js with functions.js files
